In [1]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD

2023-03-04 19:29:17.285922: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
x_train = np.array([[0,0],
                    [0,1],
                    [1,0],
                    [1,1]])
y_train = np.array([[0],
                    [1],
                    [1],
                    [0]])

In [3]:
model = keras.Sequential()

2023-03-04 19:29:20.907254: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
num_neurons = 10

In [5]:
model = keras.Sequential()
model.add(layers.Dense(num_neurons, input_dim = 2, activation = 'tanh'))
model.add(layers.Dense(1, activation = 'sigmoid'))
#model.add(layers.Activation('sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [6]:
sgd = SGD(learning_rate = 0.1)

In [7]:
model.compile(loss = 'binary_crossentropy', optimizer=sgd, metrics = ['accuracy'])

In [8]:
model.predict(x_train)

1/1 [==============================] - 0s 102ms/step


array([[0.5       ],
       [0.49495506],
       [0.44193634],
       [0.4398446 ]], dtype=float32)

In [9]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 414ms/step - loss: 0.6981 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6967 - accuracy: 0.2500
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6953 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6942 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6931 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6922 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6913 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6905 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6898 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6891 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

In [10]:
model.predict(x_train)

1/1 [==============================] - 0s 19ms/step


array([[0.449571  ],
       [0.55405253],
       [0.53250253],
       [0.5241626 ]], dtype=float32)

In [11]:
model.fit(x_train, y_train, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6401 - accuracy: 0.7500
Epoch 2/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6394 - accuracy: 0.7500
Epoch 3/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6388 - accuracy: 0.7500
Epoch 4/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.6381 - accuracy: 0.7500
Epoch 5/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6374 - accuracy: 0.7500
Epoch 6/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6367 - accuracy: 0.7500
Epoch 7/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6361 - accuracy: 0.7500
Epoch 8/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6354 - accuracy: 0.7500
Epoch 9/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6347 - accuracy: 0.7500
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6340 - accuracy: 0.7500
Epoch 11/1000
1/1

In [12]:
model.predict(x_train)

1/1 [==============================] - 0s 20ms/step


array([[0.02156611],
       [0.9687715 ],
       [0.9681692 ],
       [0.04223124]], dtype=float32)

In [13]:
x_test = np.array([[0,0],
                   [1,1]])
y_test = np.array([[0],
                    [0]])

In [14]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.03247547894716263
Test accuracy: 1.0
