In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD

2023-04-26 15:27:32.261705: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
x_train = np.array([[0,0],
                    [0,1],
                    [1,0],
                    [1,1]])
y_train = np.array([[0],
                    [1],
                    [1],
                    [0]])

In [ ]:
model = keras.Sequential()

In [ ]:
num_neurons = 10

In [ ]:
model = keras.Sequential()
model.add(layers.Dense(num_neurons, input_dim = 2, activation = 'tanh'))
model.add(layers.Dense(1, activation = 'sigmoid'))
#model.add(layers.Activation('sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [ ]:
sgd = SGD(learning_rate = 0.1)

In [ ]:
model.compile(loss = 'binary_crossentropy', optimizer=sgd, metrics = ['accuracy'])

In [ ]:
model.predict(x_train)

1/1 [==============================] - 0s 172ms/step


array([[0.5       ],
       [0.6647533 ],
       [0.39058453],
       [0.5739853 ]], dtype=float32)

In [ ]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 381ms/step - loss: 0.7237 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7226 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7215 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7204 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 0.7194 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7184 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7175 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7166 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7157 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7148 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

In [ ]:
model.predict(x_train)

1/1 [==============================] - 0s 21ms/step


array([[0.45071498],
       [0.5787807 ],
       [0.47224125],
       [0.5405123 ]], dtype=float32)

In [ ]:
model.fit(x_train, y_train, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6685 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6680 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6675 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6671 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.6666 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.6661 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.6657 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.6652 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6647 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6642 - accuracy: 0.5000
Epoch 11/1000
1

In [ ]:
model.predict(x_train)

1/1 [==============================] - 0s 19ms/step


array([[0.04063406],
       [0.9551418 ],
       [0.94616646],
       [0.0657511 ]], dtype=float32)

In [ ]:
x_test = np.array([[0,0],
                   [1,1]])
y_test = np.array([[0],
                    [0]])

In [ ]:
score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.05474754050374031
Test accuracy: 1.0
